### ISSUE TITLE
"Delete All" Button in a Collection fails

### ISSUE THREAD

**Issue by KZellweger** [mongo-express/mongo-express#1328]
### Environment: 
Docker Image mongo-express:latest (tested with 1-20 and 1-18 as well)
Docker Image mongo:latest

### Expected behavoir: 
Pressing "Delete All" in a collection should delete all the documents from the current collection.

![image](https://github.com/mongo-express/mongo-express/assets/47775177/2fa4da0f-c7c6-4335-9b05-f10b00e766da)

### Actual behavoir
Pressing the button results in a error page. 
the query `?key=&value=&type=&query={}&projection=&runAggregate=false` is inserted after the collection name in the url

Error Message in the Container Log:

```2023-10-27 08:21:27 /node_modules/mongo-express/lib/routes/collection.js:84
2023-10-27 08:21:27           ...result,
2023-10-27 08:21:27              ^
2023-10-27 08:21:27 
2023-10-27 08:21:27 TypeError: result is not iterable
2023-10-27 08:21:27     at exp._buildMongoQuery (/node_modules/mongo-express/lib/routes/collection.js:84:14)
2023-10-27 08:21:27     at exp.deleteCollection (/node_modules/mongo-express/lib/routes/collection.js:448:23)
2023-10-27 08:21:27     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
2023-10-27 08:21:27     at next (/node_modules/express/lib/router/route.js:144:13)
2023-10-27 08:21:27     at mongoMiddleware (/node_modules/mongo-express/lib/router.js:260:5)
2023-10-27 08:21:27     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
2023-10-27 08:21:27     at next (/node_modules/express/lib/router/route.js:144:13)
2023-10-27 08:21:27     at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
2023-10-27 08:21:27     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
2023-10-27 08:21:27     at /node_modules/express/lib/router/index.js:284:15```

**Comment by rtritto** [comment]
`_buildMongoQuery` is removed in #1009
Please use a newer Docker image version.

**Comment by KZellweger** [comment]
@rtritto thank you for your response. 
I am using the latest image versions 

```
REPOSITORY      TAG       DIGEST                                                                    IMAGE ID       CREATED       SIZE
mongo-express   latest    sha256:05b7441d57d9e0f74f29b04b9a8fda3fabd4bb5021474cec4ab3956b07aed804   156c460699a5   11 days ago   247MB
mongo           latest    sha256:d341a86584b96eb665345a8f5b35fba8695ee1d0618fd012ec4696223a3d6c62   ee3b4d1239f1   2 weeks ago   748MB
```

Even when i specify the current latest digest from docker hub the error still persists. 

```
# Starts a Mongo DB Server
version: '3.1'

services:
  xenio-mongo-db:
    image: mongo
    restart: always
    container_name: xenio-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/var/mongo/data
    environment:
      MONGO_INITDB_DATABASE: xenio-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express@sha256:e8f1096fc88d5566df50923b4b3556f74510ae9e0a8f0f29e4b854d444b30b18
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@xenio-mongo-db:27017/

volumes:
  mongo-data:
```
