### ISSUE TITLE
Latest Update 1.0.2-20 Opens Admin Panel to Anyone if using Basic Auth

### ISSUE THREAD

**Issue by FrancisBaileyH** [mongo-express/mongo-express#1370]
Hi team,

Firstly, I wanted to say thank you for fixing the mongo express build, it's in a much better place than 3 months ago. I wanted to quickly point a potential security issue for those who were using basic auth to access the admin panel.

Prior to `1.0.2-20` having the following config was sufficient to enforce username/password entry:
```
version: '3'
services:
  mongodb-express:
    network_mode: "host"
    image: mongo-express:1.0.0-20
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://127.0.0.1:27017/
      ME_CONFIG_BASICAUTH_USERNAME: some-username
      ME_CONFIG_BASICAUTH_PASSWORD: some-password
```

However, with the latest update these BASIC AUTH configs are ignored unless the following is also present:
```
ME_CONFIG_BASICAUTH: 'true'
```
I see this config has been documented, but given that users may simply be bumping version numbers they may not be aware that their mongo-express instance is now silently accessible to anyone. It was some good fortune that I decided to test from a private browser and noticed the issue. But perhaps it's possible to throw an error if we see the BASIC_AUTH configs present without `ME_CONFIG_BASICAUTH: 'true'` also enabled.
