### ISSUE TITLE
docker-entrypoint.sh: line 15: mongo: Name does not resolve only for 6.0 - working in 7.0

### ISSUE THREAD

**Issue by bigbulb** [mongo-express/mongo-express#1588]
Hello,

I've been following the instructions at [https://hub.docker.com/_/mongo] to connect to MongoDB from another Docker container. It is working fine as below with mongo 7.0.0:

```
services:
  mongo:
    image: mongo:7.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
```

I am trying to set it up for mongo v6.0.15, as follow:
```
services:
  mongo:
    image: mongo:7.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

```

However, for 6.0, I am getting various errors and the 

_mongo-express-1  | Fri Jun 28 16:58:21 UTC 2024 retrying to connect to mongo:27017 (2/10)
mongo-express-1  | /docker-entrypoint.sh: line 15: mongo: Name does not resolve
Could not connect to database using connectionString: mongodb://root:****@mongo:27017/"_

Any idea? Is the setup different for 6.0?

**Comment by xTudoS** [comment]
it sounds like mongo-express is starting before mongo container. Did you put that mongo-express depends on mongo container?

**Comment by xTudoS** [comment]
Hello @bigbulb , any update?

Did you tried to put mongo in depends_on for  mongo-express?

like:

```
mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
   depends_on:
     - mongo
```
