### ISSUE TITLE
cant access Databases I can access with 1.0.2 docker

### ISSUE THREAD

**Issue by 1muen** [mongo-express/mongo-express#1619]
![grafik](https://github.com/user-attachments/assets/a6030f1a-0485-4c52-9af5-5ec011250c33)
I tried the v1.0.3RC and master like this:
```
export ME_CONFIG_MONGODB_URL="mongodb://admin:admin@localhost:27017" && export PORT=9081 && pnpm run start-dev
```
(you see the result on the left side of the screenshot)
To access the same DB I use in my docker-compose file:
```
  mongo:
    networks:
      - dev
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped
    # command: mongod --verbose

  mongo-express:
    networks:
      - dev
    image: mongo-express:latest
    ports:
      - 9002:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin123"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "admin"
      ME_CONFIG_MONGODB_SERVER: "mongo"
    depends_on:
      - mongo
    restart: unless-stopped
```
Why is only the test DB shown in master/1.0.3RC? Its the same test DB I access with both versions.
