### ISSUE TITLE
Docker image removed existing DB on install

### ISSUE THREAD

**Issue by adamasantares** [mongo-express/mongo-express#1675]
Every time I build mongo-express docker container (last official image) it totally drop all existing databases. First time I thought it was my mistake, but I tested it few times on different server and it really drops databases. I have no idea why, but it's dangerous to use it on production server at the moment.

That's my docker config:

```
services:

  mongodb:
    container_name: "${COMPOSE_PROJECT_NAME}-mongodb"
    build:
      # there is just ubuntu 22 + RUN apt-get install mongodb-org -y + some additional packages I needed, works well for all my projects, there in no issues 100%
      context: ./scaffolding/mongodb  
    restart: always
    volumes:
      - mongo-volume:/data/db
    networks:
      - default

  mongo-express:
    container_name: "${COMPOSE_PROJECT_NAME}-mongo-express"
    image: "mongo-express"
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_EXPRESS_USER}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_EXPRESS_PASSWORD}"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: "${COMPOSE_PROJECT_NAME}-mongodb"
  networks:
      - default
```

Just wan to say that I've tried to use mongo-express for first time and had no problem of accidentally dropping databases before.

So, lets say before build mongo-express (M.E.) container I had database "my_project", after install M.E. I see those databases only:

```
{
	"databases" : [
		{
			"name" : "admin",
			"sizeOnDisk" : NumberLong(40960),
			"empty" : false
		},
		{
			"name" : "config",
			"sizeOnDisk" : NumberLong(12288),
			"empty" : false
		},
		{
			"name" : "local",
			"sizeOnDisk" : NumberLong(40960),
			"empty" : false
		}
	],
	"totalSize" : NumberLong(94208),
	"totalSizeMb" : NumberLong(0),
	"ok" : 1
}
```

How can it be?
