### ISSUE TITLE
Hardcoded ME_CONFIG_MONGODB_URL Prevents Kubernetes Users from Setting Custom MongoDB URL

### ISSUE THREAD

**Issue by Anjal-Poudel** [mongo-express/mongo-express#1718]
The official **mongo-express:latest** Docker image has a hardcoded environment variable in its Dockerfile:
ENV ME_CONFIG_MONGODB_URL="_mongodb://mongo:27017_"

This prevents Kubernetes users from overriding the MongoDB URL in their Deployments. Even after defining ME_CONFIG_MONGODB_URL in Kubernetes, the container still defaults to _mongodb://mongo:27017_, ignoring the user-provided value.

Additionally, the entrypoint script (docker-entrypoint.sh) relies on:

    exec 6<>/dev/tcp/$host/$port_

which does not work in all environments (e.g., Alpine Linux). This results in errors like:
     _/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument_

**🔄 Steps to Reproduce:**

**1. Deploy Mongo Express in Kubernetes using the following Deployment YAML:**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_URL
            value: "mongodb://mongodb-svc:27017"
```

**2. Check the environment variable inside the running Mongo Express pod:**
`kubectl exec -it <mongo-express-pod> -- env | grep ME_CONFIG_MONGODB_URL`

**3. Expected Output:**
`ME_CONFIG_MONGODB_URL=mongodb://mongodb-svc:27017`

**4. Actual Output:**
`ME_CONFIG_MONGODB_URL=mongodb://mongo:27017`

The container ignores the Kubernetes override and still uses the hardcoded default.

**✅ Expected Behavior:**
    The ME_CONFIG_MONGODB_URL environment variable should respect the value provided by Kubernetes.
    Hardcoded environment variables should not override user-defined values.

**💡 Suggested Fix:**

**📌 Option 1: Remove the Hardcoded ENV Line**
Remove this line from the Dockerfile:

   ` ENV ME_CONFIG_MONGODB_URL="mongodb://mongo:27017"`
      
This allows Kubernetes (or any container runtime) to fully override the variable.

**📌 Option 2: Use a Default Value Instead**
Modify the image to use a default only if the variable is not set:
      
` process.env.ME_CONFIG_MONGODB_URL = process.env.ME_CONFIG_MONGODB_URL || "mongodb://mongo:27017";`

This way, Kubernetes users can override the variable while keeping a fallback for non-Kubernetes users.

**📌 Why This Matters?**

    * This issue affects all Kubernetes users who need to connect Mongo Express to a service-discovery-based database URL.

    * Other official images (like mongo, postgres, redis) allow Kubernetes to override environment variables correctly.

    * Removing the hardcoded ENV variable would make Mongo Express more flexible for containerized environments.
    

**Thank you for maintaining Mongo Express! 🚀**
