### ISSUE TITLE
Azure Cosmos DB for Mongodb Connection

### ISSUE THREAD

**Issue by PandhuWibowo** [mongo-express/mongo-express#1741]
Hi team, 

Currently we need to connect from Azure Cosmos DB for Mongodb to mongo-express in our K8s Cluster. Somehow until now we cannot connected yet. The response always looks like this

```
Defaulted container "mongo-express" out of: mongo-express, datadog-init-apm-inject (init), datadog-lib-java-init (init), datadog-lib-js-init (init), datadog-lib-python-init (init), datadog-lib-dotnet-init (init), datadog-lib-ruby-init (init)
Waiting for [env].mongocluster.cosmos.azure.com:10255...
/docker-entrypoint.sh: line 15: [env].mongocluster.cosmos.azure.com: Name has no usable address
/docker-entrypoint.sh: line 15: /dev/tcp/[env].mongocluster.cosmos.azure.com:10255: Invalid argument
Mon Mar 17 15:36:51 UTC 2025 retrying to connect to [env].mongocluster.cosmos.azure.com:10255 (2/10)
```

Can you tell me guys, what happened with this one?

Current existing configuration looks like this. 

```
namespace: test
replicaCount: 1

image:
  repository: mongo-express
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 8081

mongodb:
  host: "[env].mongocluster.cosmos.azure.com"
  port: "10255"
  username: "[Username]"
  password: "[Password]"
  authEnabled: true
  extraArgs: "?tls=true&authMechanism=[Encryption Method]&retrywrites=false&maxIdleTimeMS=120000"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
```
