### ISSUE TITLE
Problem connecting to mongo with ssl

### ISSUE THREAD

**Issue by osher** [mongo-express/mongo-express#484]
Hi.

My docker compose section looks like so:

```
  fn-mongo-express-web:
    container_name: fn-mongo-express-web
    image: mongo-express
    networks: 
      - internal
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - "./etc/ssl/db-client.ca.crt:/etc/db-client.ca.crt:ro"
    environment:
      - "ME_CONFIG_MONGODB_SSLVALIDATE=false"
      - "ME_CONFIG_MONGODB_CA_FILE=/etc/db-client.ca.crt"
    links:
      - fn-profiles-mongo:mongo
    depends_on:
      - fn-profiles-mongo
    restart: always
```

The container complains as follows:
```
fn-mongo-express-web    | Waiting for mongo:27017...
fn-mongo-express-web    | Welcome to mongo-express
fn-mongo-express-web    | ------------------------
fn-mongo-express-web    |
fn-mongo-express-web    |
fn-mongo-express-web    | Mongo Express server listening at http://0.0.0.0:8081
fn-mongo-express-web    | Server is open to allow connections from anyone (0.0.0.0)
fn-mongo-express-web    | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
fn-mongo-express-web    |
fn-mongo-express-web    | /node_modules/mongodb/lib/server.js:265
fn-mongo-express-web    |         process.nextTick(function() { throw err; })
fn-mongo-express-web    |                                       ^
fn-mongo-express-web    | MongoError: connection 0 to mongo:27017 closed
fn-mongo-express-web    |     at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:29:11)
fn-mongo-express-web    |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:200:22)
fn-mongo-express-web    |     at Object.onceWrapper (events.js:315:30)
fn-mongo-express-web    |     at emitOne (events.js:116:13)
fn-mongo-express-web    |     at Socket.emit (events.js:211:7)
fn-mongo-express-web    |     at TCP._handle.close [as _onclose] (net.js:561:12)
```

Help anybody?

**Comment by osher** [comment]
Let me add a little more information.

The keys & certificates were created using this procedure:
https://docs.mongodb.com/manual/appendix/security/appendixA-openssl-ca/

The Mongo DB launched successfully with the PEM, and I have successfully connected to it in the shell using:
```
require('mongodb').connect('mongodb://localhost:27017/', { ssl: true, sslCa: fs.readFileSync('../etc/ssl/db-client.ca.crt')}).then( C => console.log(c=C));1
```
the paths are correct. I run a query I get the results I expect - e.g.: 
```
c.db('profiles').collection('person').find({}).toArray(console.log);1
```
this yields array of `person` records.

- i e - 
So the mongo itself is configured well.
I'm sure I'm just misconfiguring `mongo-express`, I just need a little nudge in the right direction

**Comment by osher** [comment]
If I change the `command` in my docker-compose to `sleep 1000000` I can `run -it  .. sh` and from there - I successfully connect to the DB using the same node code.

I need help in passing the CA file to the mongo-express application.

anybody can point me the right direction?

**Comment by dozoisch** [comment]
@osher I'm not sure if the FILE variable is available in the docker container, I need to cut the release from here first, which I'll try to do tonight.

**Comment by osher** [comment]
@dozoisch  - thanks.
I just made it work and came to share my results.

I made it work with the following work-around:

in docker-compose:
```
  fn-mongo-express-web:
    container_name: fn-mongo-express-web
    image: mongo-express
    networks: 
      - tailormed
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - "./etc/ssl/db-client.ca.crt:/etc/db-client.ca.crt:ro"
      #HACK: inject ca file
      - "./etc/mongo-express/config.js:/node_modules/mongo-express/config.js:ro"
      #HACKEnd
    environment:
      - "ME_CONFIG_MONGODB_CA_FILE=/etc/db-client.ca.crt"
    #  - "ME_CONFIG_MONGODB_SSL=true"
    #  - "ME_CONFIG_MONGODB_PORT=27017"
    #  - "ME_CONFIG_MONGODB_SSLVALIDATE=false"
    links:
      - fn-profiles-mongo:mongo
    depends_on:
      - fn-profiles-mongo
    command: sleep 1000000
    restart: always
```

`/etc/mongo-express/config.js`:
```
module.exports = {
  mongodb: {
    ssl: true,
    sslValidate: false,
    sslCA: [
      require('fs').readFileSync(process.env.ME_CONFIG_MONGODB_CA_FILE).toString()
    ],
  }
};
```

problems overcome:
1. `v0.49.0` does not know to pickup  ME_CONFIG_MONGODB_CA_FILE, so I had to provide it in `config.js`
2. the 3 commented out `environment` entries in docker compose - when provided - the value type gets to be string. this caused the observed error.
moving them to `config.js` preserved the type.

So when you pull them from env-vars - you have to make sure you `Number(v)` the port and `Boolean(v)` the other two flags.

**Comment by klubi** [comment]
I have the same issue, unfortunately provided hack did not work :/

I'm trying to connect to AWS DocumentDB which provides it's own pem file -> https://docs.aws.amazon.com/documentdb/latest/developerguide/getting-started.connect.html.

I have extremely simple docker-compose.yml

```yml
version: '2'

services:
    mongo-express-qa:
        image: mongo-express
        ports:
            - "127.0.0.1:8000:8081"
        volumes:
            - "./rds-combined-ca-bundle.crt:/etc/rds-combined-ca-bundle.crt:ro"
            - "./config.js:/node_modules/mongo-express/config.js:ro"
        environment:
            - "ME_CONFIG_MONGODB_CA_FILE=/etc/rds-combined-ca-bundle.crt"
            - "ME_CONFIG_MONGODB_SERVER=xxx.docdb.amazonaws.com"
            - "ME_CONFIG_BASICAUTH_USERNAME=xxx"
            - "ME_CONFIG_MONGODB_AUTH_DATABASE=admin"
            - "ME_CONFIG_BASICAUTH_PASSWORD=xxx"
            - "ME_CONFIG_MONGODB_PORT=27017"
```

But then I'm being granted with:
```
mongo-express-qa_1  | Waiting for xxx.docdb.amazonaws.com:27017...
mongo-express-qa_1  | Welcome to mongo-express
mongo-express-qa_1  | ------------------------
mongo-express-qa_1  |
mongo-express-qa_1  |
mongo-express-qa_1  | Mongo Express server listening at http://0.0.0.0:8081
mongo-express-qa_1  | Server is open to allow connections from anyone (0.0.0.0)
mongo-express-qa_1  | Database connected
mongo-express-qa_1  | Admin Database connected
mongo-express-qa_1  | unable to list databases
mongo-express-qa_1  | { MongoError: Not authorized to execute command
mongo-express-qa_1  |     at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
mongo-express-qa_1  |     at /node_modules/mongodb-core/lib/connection/pool.js:483:72
mongo-express-qa_1  |     at authenticateStragglers (/node_modules/mongodb-core/lib/connection/pool.js:429:16)
mongo-express-qa_1  |     at Connection.messageHandler (/node_modules/mongodb-core/lib/connection/pool.js:463:5)
mongo-express-qa_1  |     at TLSSocket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:319:22)
mongo-express-qa_1  |     at emitOne (events.js:116:13)
mongo-express-qa_1  |     at TLSSocket.emit (events.js:211:7)
mongo-express-qa_1  |     at addChunk (_stream_readable.js:263:12)
mongo-express-qa_1  |     at readableAddChunk (_stream_readable.js:250:11)
mongo-express-qa_1  |     at TLSSocket.Readable.push (_stream_readable.js:208:10)
mongo-express-qa_1  |   name: 'MongoError',
mongo-express-qa_1  |   message: 'Not authorized to execute command',
mongo-express-qa_1  |   ok: 0,
mongo-express-qa_1  |   errmsg: 'Not authorized to execute command',
mongo-express-qa_1  |   code: 13 }
```
