### ISSUE TITLE
Example of working docker compose replica set?

### ISSUE THREAD

**Issue by Grindv1k** [mongo-express/mongo-express#518]
I have a replica set setup via docker compose, all mongo containers on the same machine.

Using pymongo, I can connect via:

`pymongo.MongoClient(['mongodb://mongo-1:27017', 'mongodb://mongo-2:27018', 'mongodb://mongo-3:27019'], replicaSet='mongo-rs', username='my_user', password='my_pw')`

What is an example of setting up mongo-express, connecting in the same way?

`ME_CONFIG_MONGODB_SERVER` can supposedly accept a list but has anyone gotten the syntax correct?

**Comment by dvagapov** [comment]
ME_CONFIG_MONGODB_SERVER = "url.mongo-1,url.mongo-2,url.mongo-3"
ME_CONFIG_MONGODB_PORT = "27017"
ME_CONFIG_MONGODB_ADMINUSERNAME = "admin"
ME_CONFIG_MONGODB_ADMINPASSWORD = "****"
That works for me

**Comment by zubair1024** [comment]
how to make it work with docker containers containing mongodb running on different ports?

**Comment by dvagapov** [comment]
https://docs.docker.com/engine/reference/commandline/run/
docker create **--env** ME_CONFIG_MONGODB_SERVER="url.mongo-1,url.mongo-2,url.mongo-3" **--env**  ME_CONFIG_MONGODB_PORT="27017" --name mongo-express image:tag
Or 
docker create **--env-file** ./Your_file_with_ENVs --name mongo-express  image:tag

about different ports, in replica-set a port are the same for all servers in Replica

**Comment by zubair1024** [comment]
Not necessarily, I can have different ports, especially for my nosqlbooster client to work: 

```
version: "2"

services:
  mongodb-primary:
    image: "bitnami/mongodb:4.2.5"
    container_name: "mongodb-primary"
    ports:
      - "27717:27717"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_PRIMARY_HOSTNAME}
      - MONGODB_PORT_NUMBER=27717
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
      # - MONGODB_USERNAME=${MONGODB_USERNAME}
      # - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      # - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - "mongodb_master_data:/bitnami"
    networks:
      - replica-docker
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always

  mongodb-secondary:
    image: "bitnami/mongodb:4.2.5"
    container_name: "mongodb-secondary"
    ports:
      - "27718:27718"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PORT_NUMBER=27718
      - MONGODB_PRIMARY_PORT_NUMBER=27717
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_SECONDARY_HOSTNAME}
      - MONGODB_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
    volumes:
      - "mongodb_secondary_data:/bitnami"
    networks:
      - replica-docker
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always

  mongodb-arbiter:
    image: "bitnami/mongodb:4.2.5"
    container_name: "mongodb-arbiter"
    ports:
      - "27720:27720"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PORT_NUMBER=27720
      - MONGODB_PRIMARY_PORT_NUMBER=27717
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_ARBITER_HOSTNAME}
      - MONGODB_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
    volumes:
      - "mongodb_arbiter_data:/bitnami"
    networks:
      - replica-docker
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always

  mongo-express:
    image: "mongo-express:latest"
    container_name: "mongo-express"
    ports:
      - 8088:8081
    links:
      - "mongodb-primary"
    depends_on: 
      - "mongodb-primary"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGODB_PRIMARY_HOSTNAME}
      - ME_CONFIG_MONGODB_PORT=27717
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_ROOT_PASSWORD}
      # - ME_CONFIG_OPTIONS_EDITORTHEME=night
      # - ME_CONFIG_REQUEST_SIZE=100kb
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always
    
volumes:
  mongodb_master_data:
    driver: local
  mongodb_arbiter_data:
    driver: local
  mongodb_secondary_data:
    driver: local

networks:
  replica-docker:

```

**Comment by dvagapov** [comment]
Then Probably need to extend ENV ME_CONFIG_MONGODB_URL for using multiple hosts.
like : ME_CONFIG_MONGODB_URL = "mongodb://user:pass@host1:port1,host2:port2,..."

I suggest you create a request on this feature

**Comment by MichaelJCole** [comment]
That feature has been implemented, so this issue could be closed. 

https://github.com/mongo-express/mongo-express/blob/bb7e8489d1a1ee9bd1a62eadb342b437427e6eea/config.default.js

**Comment by RensTillmann** [comment]
How would on go about defining the replica set inside a docker compose file?
For instance I have a docker swarm, and I have stack running with 3 mongdb instances with replica set named `rs1`.
When inside golang I can simply define the URL to connect to this replicaset like so:

`mongodb://admin:" + url.PathEscape(GetSecret("mongo_password")) + "@mongo1,mongo2,mongo3/?authSource=admin&replicaSet=rs1"`

Which works correctly.
But I don't know where to define the `replicaSet` parameter inside the docker compose file for `mongo-express` to work.
When I just try the file below, I get this error in the logs: `Incomplete key value pair for option`.
Any idea what to do here?

```
version: '3.8'

services:
  db:
    image: mongo-express
    networks:
      - traefik-public
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo1,mongo2,mongo3"
      # ME_CONFIG_MONGODB_SERVER: "mongo1,mongo2,mongo3?replSet=rs1" # ?????
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS?Variable not set}
      # command: ["--replSet=rs1"] # ????
    deploy:
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.express.rule=Host(`express.domain.com`)
        - traefik.http.routers.express.entrypoints=http
        - traefik.http.routers.express.middlewares=https-redirect
        - traefik.http.routers.express-secure.rule=Host(`express.domain.com`)
        - traefik.http.routers.express-secure.entrypoints=https
        - traefik.http.routers.express-secure.tls.certresolver=le
        - traefik.http.routers.express-secure.middlewares=admin-auth
        - traefik.http.services.express.loadbalancer.server.port=8081

networks:
  traefik-public:
    external: true
  mongo:
    external: true
```

**Comment by RensTillmann** [comment]
So I think I might know what the issue is here, it seems to be related to the fact that my password contains a quote, even though I escaped it when defining it. Not only that, I had to only define `mongo1` in order for it to work otherwise I would get the error about not defining the replicaset (and I don't know how to define it right now, so I just leave it like that). The replicaset still works, when I make changes to via express, even though I only defined `mongo1` but perhaps I didn't quite understand that parameter then?

For instance (note the password containing a quote which is escaped when setting it via command line):
This won't work:
```
export MONGO_PASS="passwordwithquote\"restofpassword" &&
docker stack deploy --prune --resolve-image always --with-registry-auth -c /mnt/traefikcerts/express.domain.com.yml express && docker stack ps express
```

While using a password without quote works (I tested this).

```
export MONGO_PASS="passwordwithoutquote" &&
docker stack deploy --prune --resolve-image always --with-registry-auth -c /mnt/traefikcerts/express.domain.com.yml express && docker stack ps express
```

The thing here is that I can still use the password with quote to connect, For instance in my golang application it works fine.
Could this be some kind of bug in the mongo-express itself?

Compose file used:

```
version: '3.8'

services:
  db:
    image: mongo-express
    networks:
      - traefik-public
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo1"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS?Variable not set}
    deploy:
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.express.rule=Host(`express.domain.com`)
        - traefik.http.routers.express.entrypoints=http
        - traefik.http.routers.express.middlewares=https-redirect
        - traefik.http.routers.express-secure.rule=Host(`express.domain.com`)
        - traefik.http.routers.express-secure.entrypoints=https
        - traefik.http.routers.express-secure.tls.certresolver=le
        - traefik.http.routers.express-secure.middlewares=admin-auth
        - traefik.http.services.express.loadbalancer.server.port=8081

networks:
  traefik-public:
    external: true
  mongo:
    external: true
```
