### ISSUE TITLE
How Server Time is showed up?

### ISSUE THREAD

**Issue by ricardo-dlc** [mongo-express/mongo-express#567]
I have the following files:

docker-compose.yml
```yaml
version: "3.7"
services:
  mongo:
    container_name: mongo-dev
    hostname: mongo-dev
    build:
      context: ./mongo
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo/data/db:/data/db
      - ./mongo/data/configdb:/data/configdb
  mongo-express:
    container_name: mongo-express-dev
    hostname: mongo-express-dev
    build:
      context: ./mongo-express
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
```

Dockerfile for mongo service:
```
FROM mongo

ENV TZ=America/Cancun

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

Dockerfile for mongo-express service:
```
FROM mongo-express

ENV TZ=America/Cancun

RUN apk add --no-cache tzdata

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

So when I enter to the Mongo Express admin I expect to see the container's time, i.e. in both containers I get:

```console
root@mongo-dev:/# date
Mon Apr 27 21:11:27 EST 2020
```

> Note: Even when the cointainer is running up the service, the expected time is showed

``` console
mongo-dev        | 2020-04-27T21:1:27.943-0500 I  NETWORK  [listener] waiting for connections on port 27017
```

 But the time displayed in Mongo Express is:

Server Time | Tue, 28 Apr 2020 02:11:27 GMT
-- | --

How would I be able to see the local time in mongo-express?
