### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by rafales** [mongo-express/mongo-express#597]
This happens with fresh docker setup when I'm attempting to view a database.

docker-compose config:

```yaml
version: "3.4"
services:
  db:
    image: mongo:4.4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_SERVER: db
  ```

Error:

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/919812/91589400-e87ba580-e959-11ea-9bef-fbef1396dc59.png">
