### ISSUE TITLE
Cannot Read BASICAUTH_USERNAME/PASSWORD from .env file

### ISSUE THREAD

**Issue by PunkmeisterDuy** [mongo-express/mongo-express#598]
I am using docker-compose where I set the environmental variables to be: 

environment:
                        - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
                        - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}

only when I do:

environment:
                        - ME_CONFIG_BASICAUTH_USERNAME="username"
                        - ME_CONFIG_BASICAUTH_PASSWORD="password"

it works there, but I want to make it so you can edit the credentials easily.

for some reason when i do the environmental variables for mongoDB it works:

environment:
                        - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
                        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

here is my env file

MONGO_ROOT_USER=admin
MONGO_ROOT_PASSWORD=admin
MONGOEXPRESS_LOGIN=punkmeister
MONGOEXPRESS_PASSWORD=testingStuff

**Comment by knickers** [comment]
I copy-pasted your settings into a new project and it worked for me :shrug:

```yml
version: '3'

services:
    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        depends_on:
            - mongo

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
```
```env
MONGO_ROOT_USER=admin
MONGO_ROOT_PASSWORD=admin
MONGOEXPRESS_LOGIN=punkmeister
MONGOEXPRESS_PASSWORD=testingStuff
```

 Are there any other env settings in your project that might be conflicting?

Could there be white space errors in your yml file? If there are tabs instead of spaces, that can cause problems.
