### ISSUE TITLE
web browser error: "Cannot GET /"

### ISSUE THREAD

**Issue by oz42** [mongo-express/mongo-express#635]
I am using nginx as a reverse proxy and have defined `ME_CONFIG_SITE_BASEURL=/me/`.
But when I browse to `https://foo.bar/me/`, I get the error message "Cannot GET /".

nginx.conf config snippet:

```
        location /me/ {
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://127.0.0.1:8081/;
        }

```

**Comment by souchprod** [comment]
Same issue here, no ideas since last year ?

**Comment by coxato** [comment]
hi, same here, did you solve the problem?

**Comment by mersed** [comment]
ME_CONFIG_SITE_BASEURL Seems to have issues ... I can make it work with ME_CONFIG_SITE_BASEURL, however css and js files are not loaded, hence its not working properly.

**Comment by CodingByMoMo** [comment]
Hi.
I encounter this problem today and solve it.
So I want to share my solution.

I run MongoDB and mongo-express on docker.
I get the same message as the issue title what I believe I do wrong was bad nginx configuration.
I made proxy look like that and it caused the problem  "Cannot GET /".
```
location /mongoadmin  {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://localhost:8081/;
   }
```
So change it to this and it works properly.
```
location /mongoadmin {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://localhost:8081/mongoadmin;
   }
```

But I had missing CSS files now.
I resolve that problem by editing docker-compose.
I bind catalog ./data to /data/db on both mongo container and mongo-express
And it's work.
Here is my docker-compose file

```
mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - main-net

  mongo-express:
    image: mongo-express
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
      ME_CONFIG_SITE_BASEURL: /mongoadmin
    networks:
      - main-net
networks:
  main-net:
volumes:
  db_data:
```
I start my journey with making web apps recently so my solution is not perfect.
But I hope I will help someone.

**Comment by carloszimm** [comment]
The CSS and JS file loading problem can be solved by following a similar approach mentioned in this thread (at least it worked for me): https://github.com/itsgoingd/clockwork/issues/340#issuecomment-1866376855

**Comment by HeisenbergK** [comment]
Hello,

I am having the same exact issue, BUT I am also going through my IP, therefore it CAN't be an issue with nginx.

**docker-compose:**
```
services:
  mongo:
    image: mongo:latest
    container_name: bootcore-mongo
    restart: unless-stopped
    volumes:
      - /usr/local/bootcore/mongo:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    container_name: bootcore-mongo-express
    restart: unless-stopped
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://bootcore-mongo:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_BASICAUTH_USERNAME=<something>
      - ME_CONFIG_BASICAUTH_PASSWORD=<something else>
```

**docker logs:**
```
Waiting for bootcore-mongo:27017...
No custom config.js found, loading config.default.js
Welcome to mongo-express 1.0.2
------------------------
Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
```

**`curl -v http://localhost:8081/` produces**:
```
* Host localhost:8081 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8081...
* Connected to localhost (::1) port 8081
> GET / HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 139
< Date: Sun, 27 Jul 2025 17:21:39 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
* Connection #0 to host localhost left intact
```
