### ISSUE TITLE
Server Status hasn't become to be shown.

### ISSUE THREAD

**Issue by mzch** [mongo-express/mongo-express#647]
Even when defined `ME_CONFIG_MONGODB_ENABLE_ADMIN=true`, Server Status isn't shown in the latest commit.
Could you tell me how to fix this issue?

p.s.
Perhaps typo, too.
```diff
--- config.default.js.bak	2020-11-21 18:05:47.978900615 -0800
+++ config.default.js	2020-11-21 18:06:15.034554702 -0800
@@ -69,7 +69,7 @@
       meConfigMongodbServer.length > 1 ? meConfigMongodbServer : meConfigMongodbServer[0]
     ) || mongo.host,
     port: process.env.ME_CONFIG_MONGODB_PORT || mongo.port,
-    dbName: process.env.ME_CONFIG_MONGODB_PORT || mongo.dbName,
+    dbName: process.env.ME_CONFIG_MONGODB_AUTH_DATABASE || mongo.dbName,

     // >>>> If you are using an admin mongodb account, or no admin account exists, fill out section below
     // >>>> Using an admin account allows you to view and edit all databases, and view stats
```

**Comment by dozoisch** [comment]
Does look like a typo

**Comment by ppizzo** [comment]
Any news on this issue?

**Comment by FriendlyNGeeks** [comment]
I have also not been able to pull server stats

**Comment by Ruppsn** [comment]
Same Problem here. 

`ME_CONFIG_MONGODB_ENABLE_ADMIN=true`

Does nothing. 

Will this be fixed or is there a workaround?

**Comment by milanbalazs** [comment]
I am also waiting for that fix....

**Comment by FriendlyNGeeks** [comment]
As far as i can tell from playing around with the var req.adminDb. it's always coming out as undefined even when you manually set it

**Comment by hihanley** [comment]
same problem

**Comment by jptamayo76** [comment]
same problem

**Comment by Jasn08** [comment]
When will this be applicable on the docker images as I am also encountering this issue with the latest image.

**Comment by SGA-max-faxalv** [comment]
As #792 is now merged, this issue should be possible to close?

**Comment by mzch** [comment]
Great! Fixed. Thanks!

**Comment by FriendlyNGeeks** [comment]
FYI the @latest image hasn't been updated through docker hub. manual update location here in screen shot
portainer attach to mongo-express bin/sh | apk add nano(used to edit file) | cd node_modules/mongo-epxress/lib | nano router.js | add mongo.mainClient.adminDb 

![image](https://user-images.githubusercontent.com/32318784/144734413-6dff703d-d31a-4c03-9cc3-e22740b2b16d.png)

**Comment by maximko** [comment]
Please update docker hub image aswell.

**Comment by giri-uno** [comment]
Still, the docker hub is not updated? any idea when this will be updated?

**Comment by MarinBarac** [comment]
I am still having this problem on docker. When will it be updated?

**Comment by BlackthornYugen** [comment]
@MarinBarac we hopefully will have a new image up in a few days on ghcr but I don't think we are currently able to deploy to dockerhub. I have a build of 1.0.0 available here for now: ghcr.io/blackthornyugen/mongo-express-docker:v1.0.0

For details on the official release progress see https://github.com/mongo-express/mongo-express-docker/pull/82

**Comment by AirP0WeR** [comment]
> 

Thanks it helps me. Docker image are still not working properly.

**Comment by LostOnTheLine** [comment]
> Please update docker hub image as well.

Curious if this is my issue or not.

I am trying to see the stats in my mongo-express image built off of

```yaml
version: '3.9'
services:
  nightscout-mongo-express:
    image: mongo-express
    container_name: nightscout-mongo-express
    depends_on:
      - nightscout-mongodb
    user: 1000:1000
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Phoenix
      - ME_CONFIG_MONGODB_ADMINUSERNAME=#USERNAME#
      - ME_CONFIG_MONGODB_ADMINPASSWORD=#PASSWORD#
      - ME_CONFIG_MONGODB_URL=mongodb://#USERNAME#:#PASSWORD#@nightscout-mongodb:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - 12081:8081
    volumes:
      - /docker/log/var/log:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
      #- /docker/cgm/nightscout/mongo-express/config.js:/node_modules/mongo-express/config.js
    restart: always
    privileged: true
    labels:
      - "com.centurylinklabs.watchtower.scope=dockerhub"
```

Since I cannot find instructions on  how exactly to `Turn on admin in config.js to view server stats!` I tried mapping the config.js file locally & changing values, adding it as an ENV variable, but no matter what I do it doesn't work. Am I doing something wrong or is it just that the Docker version still doesn't work?
