### ISSUE TITLE
Advanced query - $orderby not working

### ISSUE THREAD

**Issue by lopsided** [mongo-express/mongo-express#673]
Hi,
I have a collection with many fields and some of the columns are not visible. I want to sort/order by some fields I can't see. In the advanced query I enter: 
```
{$query: {}, $orderby: {myfield: -1}}
```
The results are shown but no ordering is applied. Entering just:
```
{$orderby: {myfield: 1}}
```
Fails to return any results.

Am I doing something wrong?

Many thanks

**Comment by JafarAkhondali** [comment]
Hello @lopsided 
Please attach your installation method and the version you are using.

**Comment by lopsided** [comment]
I followed the method described here: https://hub.docker.com/_/mongo/

I've just pulled the latest image and re-checked.

```
version: '3.8'

services:
  mongo:
    image: mongo:4.4-bionic
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
```
