### ISSUE TITLE
ME_CONFIG_BASICAUTH_USERNAME and ME_CONFIG_BASICAUTH_PASSWORD disregarded in Docker Swarm

### ISSUE THREAD

**Issue by sbi-rviot** [mongo-express/mongo-express#729]
Hello,

**Context**
I have a set of test services that I was running using docker-compose. I read that docker-compose was not ideal when it comes to keep secrets in the .env, hence I moved to docker swarm in order to be able to use docker secrets.

**Command flow**
I have set up the following:
- initialize mongo and mongo-express via docker-compose (which creates the images in my server)
- launch docker swarm (which will then consume those already created images)

I run the following commands:
```
docker-compose -f dockercomposefile.yml up --build -d
docker-compose down
docker stack deploy --prune --with-registry-auth --compose-file dockerswarmfile.yml stackname
```

When testing mongo-express after the first command, I get the following popup (which is what I am expecting):

![signin](https://user-images.githubusercontent.com/47696569/124088523-4df56280-da53-11eb-9bd4-0239a3c8c1b6.PNG)

However, after the last command, this popup is not coming and I access the GUI of mongo-express directly.

Can anyone help? Thank you

**Additional information**

Here are my mongo-express service in **dockercomposefile.yml**:

```
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - entryport:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: "${ME_CONFIG_MONGODB_SERVER}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${ME_CONFIG_MONGODB_ADMINPASSWORD}"
    depends_on:
      - mongo
```

and in **dockerswarmfile.yml**:

```
  mongo-express:
    image: mongo-express
    deploy:
        restart_policy:
            condition: on-failure
    ports:
      - entryport:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: "${ME_CONFIG_MONGODB_SERVER}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${ME_CONFIG_MONGODB_ADMINPASSWORD}"
    depends_on:
      - mongo
    networks:
      - swarmnetworkname
```

Docker version:
> Client: Docker Engine - Community
>  Version:           20.10.6
>  API version:       1.41
>  Go version:        go1.13.15
>  Git commit:        370c289
>  Built:             Fri Apr  9 22:46:01 2021
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.6
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       8728dd2
>   Built:            Fri Apr  9 22:44:13 2021
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.4.4
>   GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
>  runc:
>   Version:          1.0.0-rc93
>   GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

**Comment by sbi-rviot** [comment]
**Root of the issue**

.env not read by docker swarm during docker stack deploy.

**Solution**

 ```
 mongo-express:
    image: mongo-express
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    secrets:
      - s1
      - s2
      - s3
      - s4
      - s5
    ports:
      - entryport:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/s1
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/s2
      ME_CONFIG_MONGODB_SERVER_FILE: /run/secrets/s3
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/s4
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/s5
    depends_on:
      - mongo
    networks:
      - swarmnetworkname

secrets:
  s1:
    external: true
  s2:
    external: true
  s3:
    external: true
  s4:
    external: true
  s5:
    external: true
```
