### ISSUE TITLE
Unescaped at-sign in authority section

### ISSUE THREAD

**Issue by Fethbita** [mongo-express/mongo-express#754]
While using the _FILE options with complicated passwords, the connection can't be made. Here's my compose.yml
```yaml
version: "3.9"

secrets:
  mongo_user:
    file: ./secrets/mongo_user
  mongo_password:
    file: ./secrets/mongo_password

  mongodb:
    image: mongo:latest
    secrets:
      - mongo_user
      - mongo_password
    networks:
      - network1
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    ports:
      - target: 27017
        published: 27017
    volumes:
      - type: bind
        source: ./data/mongodb
        target: /data/db

  mongo-express:
    image: mongo-express
    secrets:
      - mongo_user
      - mongo_password
    networks:
      - network1
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_password

networks:
  network1:
    external: true
```

And this is the error I get:
```
Welcome to mongo-express
------------------------


Could not connect to database using connectionString: mongodb://SywDeRixeBC4qaGYjWUn4SaPQ4BViSOjiq[ApicezexcIxTOL3mEp1:xipoHAqUHaRzYvEK1@sElHypyfufyD9ahuD3BIq3gOBfANvImIh*UGx@mongodb:27017/"
(node:7) UnhandledPromiseRejectionWarning: MongoParseError: Unescaped at-sign in authority section
    at parseConnectionString (/node_modules/mongodb/lib/core/uri_parser.js:618:21)
    at connect (/node_modules/mongodb/lib/operations/connect.js:282:3)
    at /node_modules/mongodb/lib/mongo_client.js:260:5
    at maybePromise (/node_modules/mongodb/lib/utils.js:692:3)
    at MongoClient.connect (/node_modules/mongodb/lib/mongo_client.js:256:10)
    at Function.MongoClient.connect (/node_modules/mongodb/lib/mongo_client.js:401:22)
    at /node_modules/mongo-express/lib/db.js:97:37
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/node_modules/bluebird/js/release/promise.js:209:30)
    at /node_modules/mongo-express/lib/db.js:96:37
    at Array.map (<anonymous>)
    at connect (/node_modules/mongo-express/lib/db.js:91:58)
    at router (/node_modules/mongo-express/lib/router.js:24:23)
    at middleware (/node_modules/mongo-express/lib/middleware.js:37:22)
    at bootstrap (/node_modules/mongo-express/app.js:102:36)
    at Object.<anonymous> (/node_modules/mongo-express/app.js:143:1)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
