### ISSUE TITLE
Could not connect to mongodb with ssl client certification

### ISSUE THREAD

**Issue by evilKnife** [mongo-express/mongo-express#774]
Hello!, I am trying to configure mongo-express to connect to a mongo database located on a cloud S3 server.

To authenticate, I need to pass the user/pass and user pem certificate. I have tried to do it with the mongo cli and yes, I can connect using this without problems:
`mongo -u <user> -p <pass> --authenticationDatabase admin --host <host>:<port> --sslCAFile <namefile> --ssl`

The problem is that I am not able to connect to via environment variables, I get this error:
`(node:15) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server <host>:<port> on first connect [MongoNetworkError: connection 1 to <host>:<port> closed`

I'm pretty sure it's an authentication problem. What I don't know is how I can connect to the database with the user, password and certificate through mongo-express.

The env variables that I configured was these:
- ME_CONFIG_MONGODB_CA_FILE: path/to/cert/cert.pem
- ME_CONFIG_MONGODB_SSLVALIDATE: true
- ME_CONFIG_MONGODB_URL: mongodb://<admin>:<pass>@host:port
- ME_CONFIG_MONGODB_ADMINUSERNAME: admin

thank you in advance!!

**Comment by justinpage** [comment]
Same situation as @bremme any help. 

@dozoisch I see you're somewhat active on this repo. Anyone we can reach out to for help?

**Comment by BlackthornYugen** [comment]
Mongoexpress config.js still uses the SSL syntax for the mongodb driver that has since been deprecated and partially mapped to the TLS equivalents; however, not all SSL options have the same behaviour as the TLS ones. 

See #814 and #815 for a similar issue and it's fix. Until #814 is resolved I've been using a sed command to change the config before starting mongo express:

```yml
apiVersion: v1
kind: Pod
  name: mongoexpress-app1-0
  namespace: app1
spec:
  containers:
  - command:
    - sh
    - -xc
    - |
      # sed command is a temporary hotfix due to bug on mongo express, see:
      # - https://jira.intranet.REDACTED/jira/browse/REDACTED
      # - https://github.com/mongo-express/mongo-express/issues/814
      sed -i.old 's/sslCA: .*,/sslCA: process.env.ME_CONFIG_MONGODB_CA_FILE,/; s/ssl: .*,/ssl: true,/' config.js
      diff config.js.old config.js
      node app
    env:
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mongoexpress-mongo-config
    - name: ME_CONFIG_OPTIONS_READONLY
      value: "true"
    - name: ME_CONFIG_MONGODB_URL
      value: mongodb://app1:$(MONGODB_PASSWORD)@REDACTED-docdb-cluster.cluster-REDACTED.eu-central-1.docdb.amazonaws.com:27017/?authSource=admin&tls=true
    - name: ME_CONFIG_MONGODB_CA_FILE
      value: /certs/ca.pem
    - name: ME_CONFIG_SITE_BASEURL
      value: /mongo-express/
    image: mongo-express
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /certs
      name: certs
      readOnly: true
  volumes:
  - name: certs
    secret:
      defaultMode: 420
      items:
      - key: cacert
        path: ca.pem
      secretName: mongoexpress-mongo-config
```

The container then starts up and shows this diff:

```diff
+ sed -i.old 's/sslCA: .*,/sslCA: process.env.ME_CONFIG_MONGODB_CA_FILE,/; s/ssl: .*,/ssl: true,/' config.js
+ diff config.js.old config.js
--- config.js.old
+++ config.js
@@ -93,13 +93,13 @@
connectionOptions: {
// ssl: connect to the server using secure SSL
- ssl: process.env.ME_CONFIG_MONGODB_SSL || mongo.ssl,
+ ssl: true,
// sslValidate: validate mongod server certificate against CA
sslValidate: process.env.ME_CONFIG_MONGODB_SSLVALIDATE || true,
// sslCA: array of valid CA certificates
- sslCA: sslCAFromEnv ? [sslCAFromEnv] : [],
+ sslCA: process.env.ME_CONFIG_MONGODB_CA_FILE,
```

Maybe you can do something similar until mongo express officially supports the current mongo driver.
