### ISSUE TITLE
Can't enable admin features in docker container.

### ISSUE THREAD

**Issue by RT-Tap** [mongo-express/mongo-express#809]
Hi,
I set mongo-express up relatively easily (thank you!) however I can't seem to get the admin features working.  I just have a message saying `Turn on admin in config.js to view server stats!` but I did using `ME_CONFIG_MONGODB_ENABLE_ADMIN: true` and also tried using `"true"` but no luck.  I also tried adding  `ME_CONFIG_MONGODB_AUTH_DATABASE` , `ME_CONFIG_MONGODB_AUTH_USERNAME` , `ME_CONFIG_MONGODB_AUTH_PASSWORD`, I know documentation says it is only needed for when `ME_CONFIG_MONGODB_ENABLE_ADMIN: false`  but I figured I would try anyway.

Maybe I'm doing something wrong as I can't seem to get `ME_CONFIG_OPTIONS_EDITORTHEME: midnight` working either.

Any help is greatly appreciated.

**Comment by rbprogrammer** [comment]
I am also running into this `Turn on admin in config.js to view server stats!` error.  I believe it is still there, at least with the Docker image `mongo-express:1.0.0-alpha.4`.

**Comment by pirelaurent** [comment]
yes, problem is still there  ```  Turn on admin in config.js to view server stats!```   despite ENABLE_ADMIN set to true 
**Configuration :** 
   mongo-express:1.0.0-alpha.4 image   
   Docker version 20.10.13    
   win10 pro 20H2    

**ENV** of the running node : 
``` 
>docker exec -it mongo-express env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=00a534e1402b
TERM=xterm
ME_CONFIG_BASICAUTH_PASSWORD=passwd
ME_CONFIG_MONGODB_ADMINUSERNAME=admin
ME_CONFIG_MONGODB_ADMINPASSWORD=passwd
ME_CONFIG_MONGODB_SERVER=mongodb
ME_CONFIG_BASICAUTH_USERNAME=admin
NODE_VERSION=12.22.7
YARN_VERSION=1.22.15
ME_CONFIG_EDITORTHEME=default
ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
ME_CONFIG_MONGODB_ENABLE_ADMIN=true
VCAP_APP_HOST=0.0.0.0
MONGO_EXPRESS=1.0.0-alpha.4
HOME=/root
``` 
As i was suspecting some trouble with true, 'true' or "true", I patch config.js (with exec /bin/bash then vi)  to set 
```     
  admin: process.env.ME_CONFIG_MONGODB_ENABLE_ADMIN
      ? true
      : true,
``` 
in place of 
``` 
    admin: process.env.ME_CONFIG_MONGODB_ENABLE_ADMIN
      ? process.env.ME_CONFIG_MONGODB_ENABLE_ADMIN.toLowerCase() === 'true'                                                          
      : false,
``` 
then i stop and restart this container (i verify once on line that config.js was mine with true true ) but no effect on the problem. 

sorry : bug is elsewhere, no valid answer,  but HTH .

**Comment by kaziMashry** [comment]
I'm also facing the same issue. 
Two commands were:
`docker run -p27017:27017 -d \
-e MONGO_INITDB_ROOT_USERNAME=admin \
-e MONGO_INITDB_ROOT_PASSWORD=password\
--net some-network \
--name mongoDb \
mongo`

and:
`docker run -d \
-p8081:8081 \
-e ME_CONFIG_MONGODB_ADMINUSERNAME=admin \
-e ME_CONFIG_MONGODB_ADMINPASSWORD=password \
-e ME_CONFIG_MONGODB_PORT=27017 \
--net some-network \
-e ME_CONFIG_MONGODB_SERVER=mongoDb \
--name mongo-express \
mongo-express`

**Comment by youngmind01** [comment]
i think it is the mongo-express version

**Comment by ArnoldVanN** [comment]
I'm still having the same issue with K8s. `ME_CONFIG_MONGODB_ENABLE_ADMIN` is set to true by default as stated in the Docker Hub page. But even then I still get the message: `Turn on admin in config.js to view server stats!`
Also still happens when manually setting the env variable to true.
Tried going back to an earlier version (0.54.0) like some people suggested but this only broke things further. Like only giving me access to the web page but throwing errors while trying to preform any DB actions from the UI.

**Comment by BlackthornYugen** [comment]
> The server stats were perfectly working with version 0.54 but no more with version 1.0.0. However, configurations are still the same as in the previous version (ME_CONFIG_MONGODB_ENABLE_ADMIN)
> 
> But the comment of @BlackthornYugen on [another issue (#887)](https://github.com/mongo-express/mongo-express/issues/887#issuecomment-1241432245) shows that it is possible to get this information with v1.0.0
> 
> Is there a new special configuration to add?

I don't think that has been built into an official docker image yet.

**Comment by leandroandrade** [comment]
Hi, I'm using the following docker compose file, and it works pretty well with username `admin` and password `pass`. I hope that helps.

```
version: '3'
services:
  mongodb:
    image: arm64v8/mongo:5.0
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    ports:
      - '8082:8081'
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://root:root@mongodb:27017'
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: root
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

networks:
  default:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
```
