### ISSUE TITLE
[DOCKER] - config.js `ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"` but cannot showing the "Server Stats".

### ISSUE THREAD

**Issue by igorgomeslima** [mongo-express/mongo-express#819]
Hey guys,

My `docker-compose` cannot display server info, what's wrong?

```
version: '3.1'

services:

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mytest
      MONGO_INITDB_ROOT_PASSWORD: mytest21

  mongo-express:
    container_name: mongodb-adminui
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: mongodb://mytest:mytest21@mongo:27017/
    depends_on:
      - mongo
```

**_Result_**:

![image](https://user-images.githubusercontent.com/2649181/145485201-e28273b1-4064-4565-affc-78d9d936bd99.png)

**_Expected_**:

![image](https://user-images.githubusercontent.com/2649181/145486294-1f611959-c19a-43e5-8a48-caea4ae35c9e.png)
---
### Checks:

`> bash echo` inside container to see the value of `ME_CONFIG_MONGODB_ENABLE_ADMIN` environment variable(`ENV`) defined in compose:

![image](https://user-images.githubusercontent.com/2649181/145485647-d5cf9485-9f07-4008-9721-27b37ac57ebc.png)

**Some `container` info:**

![image](https://user-images.githubusercontent.com/2649181/145488786-a168a585-0147-4667-b6b4-935b4e503473.png)

**Docker Host OS:** `> $ hostnamectl`

```
Static hostname: localhost.localdomain
Icon name: computer-vm
Chassis: vm
Machine ID: f5929bc8e1e24939bd3c6b8971adbc5f
Boot ID: b02fcbcb765f4bddbbf0a3cac3871dc4
Virtualization: microsoft
Operating System: CentOS Linux 8
CPE OS Name: cpe:/o:centos:centos:8
Kernel: Linux 4.18.0-305.3.1.el8.x86_64
Architecture: x86-64
```

I've tried the mentioned `docker-compose` on a Docker running in Windows 10 and the result is the same.

Any clue?

UPDATE:

[#647](https://github.com/mongo-express/mongo-express/issues/647#issuecomment-986167839) - Maybe the fix has been applied, but hasn't been updated through [docker hub image](https://hub.docker.com/_/mongo-express) (until today).

Cheers.
