### ISSUE TITLE
Cannot Connect to MongoDB on Kubernetes

### ISSUE THREAD

**Issue by pseymournutanix** [mongo-express/mongo-express#832]
Hello,

Quickly trying to get a MongoDB with ExpressUI running on Kuebrnetes. I created a replicaset with the Community Operator.

I then try to connect with Express but get:-

```
Welcome to mongo-express
------------------------


(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:7) UnhandledPromiseRejectionWarning: MongoError: not authorized on admin to execute command { listCollections: 1, filter: {}, cursor: {}, nameOnly: false, lsid: { id: UUID("80eaa7c9-68d1-4bed-8ef7-16d2f6da0577") }, $clusterTime: { clusterTime: Timestamp(1646676048, 1), signature: { hash: BinData(0, DFD40FD0E513B02DC40AF25024BB8658F2EDA683), keyId: 7072410023690764291 } }, $db: "admin" }
    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:453:61)
    at Connection.emit (events.js:314:20)
    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:456:10)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:625:15)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The environment variable in the Express deployment shows:-
```
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://admin:<password>@mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017/admin?replicaSet=mongodb"
```

So it seems to connect but not do anything. So the service doesn't start listening.

Any ideas please ?

**Comment by BlackthornYugen** [comment]
Can you confirm that this user has access to list collections? If you use that same connection string with the cli can you run `db.getCollectionNames()` ?

**Comment by pseymournutanix** [comment]
Thanks. No it cannot (same error as above which explains it !). Which is odd as I deployed the Operator with the admin account to have those roles - or so I thought:-

```
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
```

**Comment by BlackthornYugen** [comment]
I'm not familour with the Community Operator; would you be able to provide the charts/values to reproduce your environment? I try and see if I can get the same error on my cluster this weekend.

**Comment by pseymournutanix** [comment]
Thanks. Just using the Community Operator from https://github.com/mongodb/mongodb-kubernetes-operator

Then my manifest for that is:-
```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.7"
  security:
    authentication:
      modes: ["SCRAM"]
    tls:
      enabled: true
      optional: true
      certificateKeySecretRef:
        name: mongodb-certs
      caConfigMapRef:
        name: mongodb-tls-ca
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-user-password
type: Opaque
stringData:
  password: <my plain text PW>
```
