### ISSUE TITLE
Mongo Express does not work if you change the default Mongo's default port in Docker Compose...

### ISSUE THREAD

**Issue by john-morsley** [mongo-express/mongo-express#834]
The following works fine:

```
networks: 

    morsley_uk_network:
      driver: bridge

services:

  # Database...
  morsley_uk_people_database:
    image: mongo
    container_name: morsley_uk_people_database
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
    - morsley_uk_network

  # Database GUI...
  morsley_uk_people_database_gui:
    image: mongo-express
    container_name: morsley_uk_people_database_gui
    ports:
    - 8080:8081
    environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    - ME_CONFIG_BASICAUTH_USERNAME=
    - ME_CONFIG_BASICAUTH_PASSWORD=
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=morsley_uk_people_database
    - ME_CONFIG_MONGODB_PORT=27017
    restart: unless-stopped
    networks:
    - morsley_uk_network
    depends_on:
    - morsley_uk_people_database
```

But, when I change Mongo's default port, Mongo Express fails:

```
networks: 

    morsley_uk_network:
      driver: bridge

services:

  # Database...
  morsley_uk_people_database:
    image: mongo
    container_name: morsley_uk_people_database
    ports:
    - 27000:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
    - morsley_uk_network

  # Database GUI...
  morsley_uk_people_database_gui:
    image: mongo-express
    container_name: morsley_uk_people_database_gui
    ports:
    - 8080:8081
    environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    - ME_CONFIG_BASICAUTH_USERNAME=
    - ME_CONFIG_BASICAUTH_PASSWORD=
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=morsley_uk_people_database
    - ME_CONFIG_MONGODB_PORT=27000
    restart: unless-stopped
    networks:
    - morsley_uk_network
    depends_on:
    - morsley_uk_people_database
```

With the following error:

```
morsley_uk_people_database_gui    | Welcome to mongo-express
morsley_uk_people_database_gui    | ------------------------
morsley_uk_people_database_gui    |
morsley_uk_people_database_gui    |
morsley_uk_people_database_gui    | (node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
morsley_uk_people_database_gui    | Could not connect to database using connectionString: mongodb://root:password@morsley_uk_people_database_users:27000/"
morsley_uk_people_database_gui    | (node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [morsley_uk_people_database_users:27000] on first connect [Error: connect ECONNREFUSED 172.25.0.4:27000
morsley_uk_people_database_gui    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
morsley_uk_people_database_gui    |   name: 'MongoNetworkError'
morsley_uk_people_database_gui    | }]
morsley_uk_people_database_gui    |     at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
morsley_uk_people_database_gui    |     at Pool.emit (events.js:314:20)
morsley_uk_people_database_gui    |     at /node_modules/mongodb/lib/core/connection/pool.js:564:14
morsley_uk_people_database_gui    |     at /node_modules/mongodb/lib/core/connection/pool.js:1000:11
morsley_uk_people_database_gui    |     at /node_modules/mongodb/lib/core/connection/connect.js:32:7
morsley_uk_people_database_gui    |     at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)
morsley_uk_people_database_gui    |     at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)
morsley_uk_people_database_gui    |     at Object.onceWrapper (events.js:421:26)
morsley_uk_people_database_gui    |     at Socket.emit (events.js:314:20)
morsley_uk_people_database_gui    |     at emitErrorNT (internal/streams/destroy.js:92:8)
morsley_uk_people_database_gui    |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
morsley_uk_people_database_gui    |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
morsley_uk_people_database_gui    | (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
morsley_uk_people_database_gui    | (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
morsley_uk_people_database_gui exited with code 0
```

Any idea what is happening!?
