### ISSUE TITLE
Import not work

### ISSUE THREAD

**Issue by rtritto** [mongo-express/mongo-express#991]
## Steps to reproduce
- Go to document listing `http://localhost:8081/db/:db/:collection`
- Click `Import --mongoexport json` button
- Choose a json file

## Response:
Body: Bad file
```yml
Request URL: http://localhost:8081/db/:db/import/:collection
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 127.0.0.1:8081
Referrer Policy: strict-origin-when-cross-origin
```
